require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.3
  NewCops: enable

Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'

Rails/Output:
  Exclude:
    - 'db/seeds.rb'